name: flublog
description: A flutter application for blog

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0

  cached_network_image: ^3.2.0

  cloud_firestore: ^3.1.10

  connectivity_plus: ^2.2.1

  cupertino_icons: ^1.0.2

  device_info_plus: ^3.2.2

  firebase_analytics: ^9.1.2

  firebase_auth: ^3.3.11

  firebase_core: ^1.13.1

  firebase_crashlytics: ^2.5.3

  firebase_dynamic_links: ^4.1.1

  firebase_performance: ^0.8.0+7

  firebase_storage: ^10.2.9

  flex_color_scheme: ^4.2.0

  flutter:
    sdk: flutter

  flutter_secure_storage: ^5.0.2

  get: ^4.6.1

  get_ip_address: ^0.0.5

  google_fonts: ^2.3.1

  hive: ^2.0.6

  image_picker: ^0.8.4+11

  intl: ^0.17.0

  share_plus: ^4.0.1

dev_dependencies:
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter

  get_test: ^4.0.1

flutter:

  uses-material-design: true