name: get_ip_address
description: A package to get the ip address of the current device. Uses https://api64.ipify.org to get the system IP.
version: 1.0.0
homepage: https://github.com/pradyotprksh/ip_address

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^1.0.0

dev_dependencies:
  test: any